Add support for /r/programming as news source
Bunchhieng/hnreader pull request #11
Opened 2018-10-03 18:54 UTC by plorefice

This addresses and solves #3 by introducing the `--source` option with allowed values `hn` and `reddit` (and a bit of infrastructure to easily expand to new sources).

2018-10-03 19:45 UTC, Bunchhieng requested changes
Nicely done! Overall looks good. Please update the count for the tab to open.

2018-10-03 19:45 UTC, Bunchhieng commented on main.go
> +	if err != nil {
nit: you can call `handleError(err)` here.

2018-10-03 19:45 UTC, Bunchhieng commented on main.go
> +			Count: 10,
Should this be `Count: count`

2018-10-04 06:35 UTC, plorefice commented
@Bunchhieng fixed! :)

2018-10-04 12:59 UTC, Bunchhieng approved these changes

2018-10-04 12:59 UTC, merged